whatis("Name: rocm-afar")
whatis("Version: 8743")
whatis("Category: compiler")
whatis("URL: https://repo.radeon.com/rocm/misc/flang/rocm-afar-8873-drop-22.2.0-alma.tar.bz2")

local base = "/appl/local/csc/soft/eng/elmer/rocm-afar-8873-drop-22.2.0"

depends_on('LUMI/24.03')
depends_on('partition/G')
depends_on('buildtools/24.03')
depends_on('rocm/6.2.2')

append_path("LD_LIBRARY_PATH", "/lib64")
append_path("LD_LIBRARY_PATH", "/lib")
prepend_path("LD_LIBRARY_PATH", pathJoin(base, "lib"))
prepend_path("LD_LIBRARY_PATH", pathJoin(base, "llvm/lib"))
prepend_path("LIBRARY_PATH", pathJoin(base, "lib"))
prepend_path("LIBRARY_PATH", pathJoin(base, "llvm/lib"))
prepend_path("C_INCLUDE_PATH", pathJoin(base, "include"))
prepend_path("CPLUS_INCLUDE_PATH", pathJoin(base, "include"))
prepend_path("CPATH", pathJoin(base, "include"))
prepend_path("PATH", pathJoin(base, "bin"))
prepend_path("PATH", pathJoin(base, "llvm/bin"))
prepend_path("INCLUDE", pathJoin(base, "include"))
prepend_path("MANPATH", pathJoin(base, "share", "man"))
--prepend_path("MODULEPATH",pathJoin(mbase, "Compiler", compiler))
pushenv("DEVICE_LIB_PATH", pathJoin(base, "amdgcn/bitcode"))
pushenv("ROCM_RUNTIME_PATH",base)
pushenv("CC", 'amdclang')
pushenv("CXX", 'amdclang++')
pushenv("FC", 'amdflang-new')
pushenv("F77", 'amdflang-new')
pushenv("LLVM_PATH", base)
pushenv("ROCM_PATH", base)
pushenv("HIP_PATH", base)
pushenv("AMDFLANG_DIR", base)
pushenv("AMDFLANG_MPICH_DIR", pathJoin(base,"mpich-3.4a2-install")
